### ISSUE TITLE
Add ERM19264 UC1609 display support

### ISSUE THREAD

**Issue by mikelemo** [olikraus/u8g2#1565]
Noticed the ERM19264 UC1609 was missing not sure how easy or hard of conversion to support this display would be but I've found the datasheet for the controller I'd love to get some guidance on how the u8g2 works internally per SPI display to help add support to it.

[Aliexx link](https://www.aliexpress.com/item/4001167985085.html?spm=a2g0o.cart.0.0.2ef43c00I1rGn4&mp=1)

[UC1609 Datasheet](https://www.buydisplay.com/download/ic/UC1609_Datasheet.pdf)

**Comment by mikelemo** [comment]
UC1610 edited Template:

`/*

  u8x8_d_uc1610.c
  
  Universal 8bit Graphics Library (https://github.com/olikraus/u8g2/)

  Copyright (c) 2016, olikraus@gmail.com
  All rights reserved.

  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this list 
    of conditions and the following disclaimer.
    
  * Redistributions in binary form must reproduce the above copyright notice, this 
    list of conditions and the following disclaimer in the documentation and/or other 
    materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  

  
  cad001
  
*/
#include "u8x8.h"




static const uint8_t u8x8_d_uc1609_erm19264_init_seq[] = {
    
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */

  U8X8_CA(0x0f1, 0x067),		/* set COM end (display height-1) */
  U8X8_C(0x0c0),            			/* SEG & COM normal */
  U8X8_C(0x040),            			/* set scroll line lsb to zero */
  U8X8_C(0x050),            			/* set scroll line msb to zero */
  U8X8_C(0x02b),            			/* set panelloading */
  U8X8_C(0x0eb),            			/* set bias 1/2 */  
  U8X8_CA(0x081, 0x05f),            	/* set contrast */
  
  /*
    AC0:	0: stop at boundary, 1: increment by one
    AC1: 	0: first column then page, 1: first page, then column increment
    AC2:	0: increment page adr, 1: decrement page adr.
  */
  U8X8_C(0x08b),            			/* set auto increment, low bits are AC2 AC1 AC0 */
  
  /*
    LC0:	0
    MX:	Mirror X
    MY:	Mirror Y
  */  
  U8X8_C(0x0c0),            			/* low bits are MY, MX, LC0 */
  
  U8X8_C(0x0f8),            			// window mode off
  U8X8_C(0x010),		                // col high
  U8X8_C(0x000),		                // col low
  U8X8_C(0x0b0),		                // page
  
  U8X8_C(0x0a6),            			/* set normal pixel mode (not inverse) */
  U8X8_C(0x0a4),            			/* set normal pixel mode (not all on) */

  /* test code 
  U8X8_C(0x0af),		                // display on 
  U8X8_C(0x0f8),            			// window mode off
  U8X8_CA(0x0f4, 0),			// set window
  U8X8_CA(0x0f5, 0),
  U8X8_CA(0x0f6, 4),
  U8X8_CA(0x0f7, 1),
  U8X8_C(0x0f9),            			// window mode on
  U8X8_D1(0x03),
  U8X8_D1(0x0c0),
  U8X8_D1(0x0ff),
  U8X8_D1(0x0ff),
  U8X8_D1(0x0ff),
  U8X8_D1(0x0ff),
  U8X8_D1(0x0ff),
  U8X8_D1(0x0ff),
  */
  
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};

static const uint8_t u8x8_d_uc1609_erm19264_powersave0_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  U8X8_C(0x0af),		                /* display on, UC1610 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};

static const uint8_t u8x8_d_uc1609_erm19264_powersave1_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  U8X8_C(0x0ae),		                /* display off,  UC1610 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};

static const uint8_t u8x8_d_uc1609_erm19264_flip0_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  /*
    LC0:	0
    MX:	Mirror X
    MY:	Mirror Y
  */  
  U8X8_C(0x0c0),            			/* low bits are MY, MX, LC0 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};

static const uint8_t u8x8_d_uc1609_erm19264_flip1_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  /*
    LC0:	0
    MX:	Mirror X
    MY:	Mirror Y
  */  
  U8X8_C(0x0c6),            			/* low bits are MY, MX, LC0 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};


/* 
  UC1610 has two chip select inputs (CS0 and CS1).
  CS0 is low active, CS1 is high active. It will depend on the display
  module whether the display has a is low or high active chip select.
*/

static const u8x8_display_info_t u8x8_uc1609_display_info =
{
  /* chip_enable_level = */ 0,
  /* chip_disable_level = */ 1,
  
  /* post_chip_enable_wait_ns = */ 15,
  /* pre_chip_disable_wait_ns = */ 15,
  /* reset_pulse_width_ms = */ 1, 
  /* post_reset_wait_ms = */ 6, 
  /* sda_setup_time_ns = */ 30,	
  /* sck_pulse_width_ns = */ 63,	/* half of cycle time (125ns cycle time according to datasheet) --> 8MHz clock */
  /* sck_clock_hz = */ 8000000UL,	/* since Arduino 1.6.0, the SPI bus speed in Hz. Should be  1000000000/sck_pulse_width_ns */
  /* spi_mode = */ 0,		/* active high, rising edge */
  /* i2c_bus_clock_100kHz = */ 4,
  /* data_setup_time_ns = */ 30,
  /* write_pulse_width_ns = */ 40,
  /* tile_width = */ 20,		
  /* tile_hight = */ 13,		/* height of 13*8=104 pixel */
  /* default_x_offset = */ 0,
  /* flipmode_x_offset = */ 0,
  /* pixel_width = */ 194,
  /* pixel_height = */ 92
};


/*
  RAM Organization:
  D0  Pix0
  D1
  D2  Pix1
  D3
  D4  Pix2
  D5
  D6  Pix3
  D7    
  D0  Pix4
  D1
  D2  Pix5
  D3
  D4  Pix6
  D5
  D6  Pix7
  D7    


*/
static uint8_t *u8x8_convert_tile_for_uc1609(uint8_t *t)
{
  uint8_t i;
  uint16_t r;
  static uint8_t buf[16];
  uint8_t *pbuf = buf;

  for( i = 0; i < 8; i++ )
  {
    r = u8x8_upscale_byte(*t++);
    *pbuf++ = r & 255;
    r >>= 8;
    *pbuf++ = r;
  }
  return buf;
}

uint8_t u8x8_d_uc1609_ae_erm19294(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
  uint8_t x, c, page;
  uint8_t *ptr;
  switch(msg)
  {
    case U8X8_MSG_DISPLAY_SETUP_MEMORY:
      u8x8_d_helper_display_setup_memory(u8x8, &u8x8_uc1609_display_info);
      break;
    case U8X8_MSG_DISPLAY_INIT:
      u8x8_d_helper_display_init(u8x8);
      u8x8_cad_SendSequence(u8x8, u8x8_d_uc1609_erm19264_init_seq);
      break;
    case U8X8_MSG_DISPLAY_SET_POWER_SAVE:
      if ( arg_int == 0 )
	u8x8_cad_SendSequence(u8x8, u8x8_d_uc1609_erm19264_powersave0_seq);
      else
	u8x8_cad_SendSequence(u8x8, u8x8_d_uc1609_erm19264_powersave1_seq);
      break;
    case U8X8_MSG_DISPLAY_SET_FLIP_MODE:
      if ( arg_int == 0 )
      {
	u8x8_cad_SendSequence(u8x8, u8x8_d_uc1609_erm19264_flip0_seq);
	u8x8->x_offset = u8x8->display_info->default_x_offset;
      }
      else
      {
	u8x8_cad_SendSequence(u8x8, u8x8_d_uc1609_erm19264_flip1_seq);
	u8x8->x_offset = u8x8->display_info->flipmode_x_offset;
      }	
      break;
#ifdef U8X8_WITH_SET_CONTRAST
    case U8X8_MSG_DISPLAY_SET_CONTRAST:
      u8x8_cad_StartTransfer(u8x8);
      u8x8_cad_SendCmd(u8x8, 0x081 );
      u8x8_cad_SendArg(u8x8, arg_int  );	/* uc1610 has range from 0 to 255 */
      u8x8_cad_EndTransfer(u8x8);
      break;
#endif
    case U8X8_MSG_DISPLAY_DRAW_TILE:
      u8x8_cad_StartTransfer(u8x8);

      x = ((u8x8_tile_t *)arg_ptr)->x_pos;
      x *= 8;
      x += u8x8->x_offset;
    
      page = (((u8x8_tile_t *)arg_ptr)->y_pos);
      page *= 2;

      u8x8_cad_SendCmd(u8x8, 0x0f8 );	/* window disable */
      
      //u8x8_cad_SendCmd(u8x8, 0x010 | (x>>4) );
      //u8x8_cad_SendCmd(u8x8, 0x000 | ((x&15)));
      //u8x8_cad_SendCmd(u8x8, 0x0b0 | page);

      u8x8_cad_SendCmd(u8x8, 0x0f4 );	/* window start column */
      u8x8_cad_SendArg(u8x8, x);
      u8x8_cad_SendCmd(u8x8, 0x0f5 );	/* window start page */
      u8x8_cad_SendArg(u8x8, page);
      u8x8_cad_SendCmd(u8x8, 0x0f6 );	/* window end column */
      u8x8_cad_SendArg(u8x8, 159);		/* end of display */
      u8x8_cad_SendCmd(u8x8, 0x0f7 );	/* window end page */
      u8x8_cad_SendArg(u8x8, page+1);
      u8x8_cad_SendCmd(u8x8, 0x0f9 );	/* window enable */
    
      do
      {
	c = ((u8x8_tile_t *)arg_ptr)->cnt;
	ptr = ((u8x8_tile_t *)arg_ptr)->tile_ptr;
	do
	{
	  u8x8_cad_SendData(u8x8, 16, u8x8_convert_tile_for_uc1609(ptr));
	  ptr += 8;
	  x += 8;
	  c--;
	} while( c > 0 );
	
	arg_int--;
      } while( arg_int > 0 );
      
      u8x8_cad_EndTransfer(u8x8);

    
      break;
    default:
      return 0;
  }
  return 1;
}
`

**Comment by olikraus** [comment]
According to the ae link i have renamed this display to u8x8_d_uc1609_slg19264.

**Comment by olikraus** [comment]
I have integrated your template and updated the repo. I have also orderted one of those LCDs but I assume shipping will take 6 weeks or so to my house.

**Comment by olikraus** [comment]
> to get some guidance on how the u8g2 works internally per SPI display to help add support to it.

You just need to call the functions prefixed with `u8x8_cad`. Depending on the user interface configuration, they will take care on the details.

**Comment by mikelemo** [comment]
> I have integrated your template and updated the repo. I have also orderted one of those LCDs but I assume shipping will take 6 weeks or so to my house.

Cool they are actually pretty good cheap thin and useable displays my e lab is just in a bit of a mess now and I ended up using the nokia5110 display as a template modified it a bit and managed to get the code compiled(last time it was just an error in the way I edited the code) but this doesn't seem to show any graphics.
Once the lab is in working condition I'll pop up the logic analyzer and see what singnals get put out if any and compare with a working arduino library for the display.

**Comment by matthijskooijman** [comment]
I'm having an issue building current master, which seems to lead me back to the commits implementing this issue.

Here's the error I get:

    u8g2/csrc/u8g2_d_setup.c:3388: undefined reference to `u8x8_d_uc1609_slg19264'

Reverting a32aa5cb83cdbae64f17da3bf2edeb4e84c02a83 fixes the build for me.

It looks like `u8x8_d_uc1609.c` was maybe forgotten to be git added before committing?

**Comment by mikelemo** [comment]
I've actually decided to order a proper logic analyzer to see how the displays likes his signals but I see you've already went a head and proceed with it.

Anyways I tryed initializing the display with 

```
u8g2_Setup_uc1609_slg19264_f(
      &u8g2,
      U8G2_R0, // Display Rotation U8G2_R0-NoRot, U8G2_R1-90Deg U8G2_R2-180Deg
      u8g2_esp32_spi_byte_cb,
      u8g2_esp32_gpio_and_delay_cb); // init u8g2 structure

```

but the copiler says it has an un defined reference to "u8x8_d_uc1609_slg19264" in the newest current version, anything I missed?

**Comment by olikraus** [comment]
> but the copiler says it has an un defined reference to "u8x8_d_uc1609_slg19264" in the newest current version, anything I missed?

I think this was pointed out by @matthijskooijman and should be solved already in the repo

**Comment by olikraus** [comment]
Hmm... I took over your template, but I think the UC1610 has a lot of differences. Actually the UC1610 is a graylevel controller, while the UC1609 is a monochrome controller... some fixes are required here.

**Comment by olikraus** [comment]
``` 
U8G2_UC1609_SLG19264_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8) 
```
I have created beta release 2.32.4. Can you test whether this works for you?

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by olikraus** [comment]
![https://raw.githubusercontent.com/wiki/olikraus/u8g2/img/uc1609_192x64.jpg](https://raw.githubusercontent.com/wiki/olikraus/u8g2/img/uc1609_192x64.jpg)

**Comment by mikelemo** [comment]
`FAILED: Distance_Roller_Meter.elf 
cmd.exe /C "cd . && C:\Coding\ESP32\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address   @CMakeFiles\Distance_Roller_Meter.elf.rsp  -o Distance_Roller_Meter.elf  && cd ."
c:/coding/esp32/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/u8g2/lib..a(u8g2_d_setup.c.obj):(.literal.u8g2_Setup_uc1609_slg19264_f+0x4): undefined reference to `u8x8_d_uc1609_slg19264'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`


I'm building the C version with esp-idf under the setup function I posted above and it 
gives me this error when trying to build after a full clean.

**To fix it** add "csrc/u8x8_d_uc1608.c" to CMakeLists.txt does it.


Beside that it works in version 2.32.6, you're the best!

Could you kindly drop a quick description on the general process you had to go throgh to adapt that display driver to the library? maybe add that to the documentation as "How to create a new u8g2 driver for a display"

![IMG_20211004_193102](https://user-images.githubusercontent.com/10002230/135889871-ccadb8bc-a63b-420a-9c33-d41721ae3e95.jpg)

**Comment by olikraus** [comment]
Thanks for the feedback.
Some documentation is here: https://github.com/olikraus/u8g2/wiki/internal#new-displays

**Comment by mikelemo** [comment]
Well I meant something with more reference to an actual development with a real world example if that's simple enough which it seems to be the case with this awesome library, but what ever thanks for help quit useful hopefully I'll be able to contribute with some other unsupported display I have in my dusplays boxs, fuess this case is closes untill then.😎

**Comment by olikraus** [comment]
I always happy to support new displays, but I always thought u8g2 covers most of them.

**Comment by mikelemo** [comment]
Slowly but surely it will, this project is on the right track.
