### ISSUE TITLE
compilation terminated, after update to 2.31.1

### ISSUE THREAD

**Issue by schroepfer** [olikraus/u8g2#1594]
Hello,
Arduino 1.8.15 terminates the compilation after update from 2.30.1 to 2.31.1

/Users/Juergen-S/Documents/Arduino/libraries/U8g2/src/clib/mui_u8g2.h:41:10: fatal error: mui.h: No such file or directory
 #include <mui.h>
                ^~~~~~~
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board Seeeduino XIAO.

**Comment by olikraus** [comment]
See also here: https://github.com/olikraus/u8g2/issues/1592

I wonder why this didn't happen for 2.30.1

**Comment by olikraus** [comment]
I have created a bugfix release for this.

**Comment by schroepfer** [comment]
Thank you! 
With 2.31.2 it compiles and works now!
